import{a as P,S as q,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const x="50366360-a8ee66cb63e3deacadb68e28f",M="https://pixabay.com/api/";async function h(t,r){const i={key:x,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await P.get(M,{params:i,timeout:5e3})).data}catch(n){throw console.error("Error fetching images:",n),new Error("Failed to fetch images from Pixabay")}}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".btn-load-more");let f;R();function R(){f=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function b(t){const r=t.map(({webformatURL:i,largeImageURL:n,tags:e,likes:o,views:a,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <div class="photo-card">
            <img src="${i}" alt="${e}" loading="lazy" />
            <div class="info">
              <p class="info-item"><b>Likes</b> ${o}</p>
              <p class="info-item"><b>Views</b> ${a}</p>
              <p class="info-item"><b>Comments</b> ${v}</p>
              <p class="info-item"><b>Downloads</b> ${S}</p>
            </div>
          </div>
        </a>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),f.refresh()}function L(){f.refresh()}function $(){g.innerHTML="",f.refresh()}function w(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}function C(){y.classList.remove("is-hidden")}function m(){y.classList.add("is-hidden")}let s=1;const I=15;let d=0,l="";const O=document.querySelector(".form"),B=document.querySelector(".btn-load-more");function E(t,r){t>=r?(c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),m()):C()}O.addEventListener("submit",async t=>{if(t.preventDefault(),s=1,l=t.target.elements["search-text"].value.trim(),l===""){c.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}w(),$(),m();try{const r=await h(l,s);if(r.hits.length===0){c.error({title:"Error",message:"No images found. Try again!",position:"topRight"}),m(),u();return}b(r.hits),L(),d=Math.ceil(r.totalHits/I),E(s,d)}catch{c.error({title:"Info",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}});B.addEventListener("click",async()=>{if(!(s>=d)){s+=1,w();try{const t=await h(l,s);b(t.hits),L(),A(),E(s,d)}catch{c.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{u()}}});function A(){const t=document.querySelector(".gallery");if(!t||!t.firstElementChild)return;const r=t.firstElementChild.getBoundingClientRect(),{height:i}=r;window.scrollBy({top:i*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
